### ISSUE TITLE
Get rid of raw json / dicts on runner commandline

### ISSUE THREAD

**Issue by veruu** [CKI-project/skt#125]
1. Bad UX, using explicit options is easier, cleaner and makes more sense
2. `ast.literal_eval()` requires some special escaping so passing strings with newlines (eg. patch subjects) is a real PITA, and it *shouldn't*

**Comment by veruu** [comment]
Re-specifying for runner-section only since reporter was fixed

**Comment by major** [comment]
I'll work on runner.
