### ISSUE TITLE
Consider using LinchPin for running tests

### ISSUE THREAD

**Issue by spbnick** [CKI-project/skt#20]
Consider using [LinchPin](https://github.com/CentOS-PaaS-SIG/linchpin) to abstract away skt's dependence on Beaker for running tests. This might allow us to support running tests with libvirt to support a simple development setup. See also [LinchPin documentation](https://linchpin.readthedocs.io/en/develop/).

We have to carefully evaluate LinchPin, though. It might be simpler and more reliable to implement our own abstraction for just two providers: Beaker and libvirt, given our relatively minor feature requirements. LinchPin might also bring in too many dependencies.

**Comment by wizardofoz123** [comment]
I skim-read LinchPin documentation and I'm not convinced it's what we currently need. 
I can write-down why & pros and cons that I see, but we'll need more opinions here anyway.
