### ISSUE TITLE
Cancel any pending jobs on SIGINT

### ISSUE THREAD

**Issue by veruu** [CKI-project/skt#283]
If the runner is interrupted, all pending jobs should be canceled (using similar logic as when a canceled job is detected).

**Comment by danghai** [comment]
@veruu could you point out the line of code for that (Or the code for canceled job is detected)? Thanks

**Comment by veruu** [comment]
@danghai just search the runner code for `Cancelled`, you should be able to find it easily.

**Comment by wizardofoz123** [comment]
This was fixed by https://github.com/CKI-project/skt/commit/5b36c4426bb0eef2977414bbb85b20154557f6a8 I think
