### ISSUE TITLE
Make the code python3-compatible

### ISSUE THREAD

**Issue by veruu** [CKI-project/skt#338]
Have skt work with both python2 and python3

**Comment by danghai** [comment]
@veruu I think we need to set `env` for both python2 and python3 in Travis?

**Comment by veruu** [comment]
That will be a part of it, sure. The main point is to check for any python2-specific code that works differently in py3 and rewrite it to work with both, and make the installation work with both pip2 and pip3. We haven't actually checked how much needs to be done or if there are any problematic modules which might block the task, but it's good to track it if somebody wants to take a look and help out.

**Comment by danghai** [comment]
Okay, I am going to look at it.

**Comment by wizardofoz123** [comment]
Done.
