### ISSUE TITLE
Implement unit tests

### ISSUE THREAD

**Issue by spbnick** [CKI-project/skt#5]

**Comment by wizardofoz123** [comment]
@spbnick What % coverage are we targeting here? I've been adding tests and skt is almost at 80% now. Of course, not all unit tests have the same added value. If we hit 100% we can basically turn the project into TDD, which I wouldn't necessarily mind. :)

**Comment by spbnick** [comment]
Hey, this was just an early TODO, I wanted *some* unit tests, I didn't have any target in mind, I think 80% is awesome :)

**Comment by wizardofoz123** [comment]
@spbnick In that case, I think you can close this issue. We may open new and more specific ones if there's need.
