### ISSUE TITLE
Need capability to build kernel outside source directory

### ISSUE THREAD

**Issue by major** [CKI-project/skt#84]
When running `skt` in a container, it would be helpful to build kernel artifacts outside the workdir where the kernel source is cloned. This would allow for artifacts to be sent to other systems.

**Comment by spbnick** [comment]
Isn't this what @stefwalter is doing in #31?

**Comment by major** [comment]
Oof, you are right -- I forgot about that one.

**Comment by veruu** [comment]
Closing as builder was removed from skt
