### ISSUE TITLE
Document interface to the kernel build

### ISSUE THREAD

**Issue by spbnick** [CKI-project/skt#88]
We need to document how skt supplies parameters to the kernel build system, which parameters, and what it expects in return. E.g. which targets it invokes, which variables it sets, how it supplies the configuration, how it finds the resulting tarballs, etc. This would allow users and developers to understand how skt works and what is and what is not important, how passing arbitrary arguments to make through skt would affect the build, and finally this would allow us to implement a tool for generating mock-up kernel sources, which checkout and build much faster than the real kernel, satisfy skt, and allow us to speedup debugging and testing dramatically.

**Comment by veruu** [comment]
Closing as builder was removed from skt
